#From https://habr.com/ru/post/540072/
version: "3.7"

services:
  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - ${NGINX_LOCAL_PORT}:80
    volumes:
      - ./www:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      main_network:
        ipv4_address: ${SUBNET_IP}.10
    depends_on:
      - php

  php:
    build:
      args:
        uname: ${PHP_UNAME}
        uid: ${PHP_UID}
        gid: ${PHP_GID}
      context: ./docker/php
    container_name: ${PROJECT_NAME}_php
    image: ${PROJECT_NAME}_php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./www:/var/www
    environment:
      COMPOSER_MEMORY_LIMIT: 2G
      XDEBUG_CONFIG: client_host=${SUBNET_IP}.1 client_port=${XDEBUG_STORM_PORT} remote_enable=1 idekey=${XDEBUG_IDEKEY}
      PHP_IDE_CONFIG: serverName=${XDEBUG_STORM_SERVER_NAME}
    networks:
      main_network:
        ipv4_address: ${SUBNET_IP}.11
    depends_on:
      - db

  db:
    image: mariadb:10.6
    restart: unless-stopped
    container_name: ${PROJECT_NAME}_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - ${DB_LOCAL_PORT}:3306
    volumes:
      - ./var/database:/var/lib/mysql
    networks:
      main_network:
        ipv4_address: ${SUBNET_IP}.12

networks:
  main_network:
    driver: bridge
    name: ${PROJECT_NAME}_main_network
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_IP}.0/24
